version: '3'

services:
  postgresql:
    image: michisig/common-db:latest
    container_name: common-db
    restart: always
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-app:
    image: michisig/auth-app:latest
    container_name: auth-app
    ports:
      - 8090:8090
    depends_on:
      postgresql:
        condition: service_healthy

  docs-app:
    image: michisig/docs-app:latest
    container_name: docs-app
    ports:
      - 8091:8091
    depends_on:
      postgresql:
        condition: service_healthy